// Catégories de news "généralistes" (pas par écurie) : chaque catégorie
// agrège plusieurs flux RSS et poste dans un seul salon Discord.
// Pour ajouter/retirer un flux, édite simplement le tableau feedUrls.

module.exports = [
  {
    name: "F1 News FR",
    emoji: "🇫🇷",
    channelId: "1376586082593931357",
    feedUrls: [
      "https://www.sports.fr/f1/feed",
      "https://sports.auto-moto.com/rss/formule-1.html",
      "https://fr.motorsport.com/rss/f1/videos/",
      "https://fr.motorsport.com/rss/f1/news/",
      "https://f1only.fr/formule1/feed/gn",
      "https://www.7sur7.be/formule-1/rss.xml",
      "https://dicodusport.fr/blog/actualites/sports-mecaniques/formule-1/feed/",
      "https://f1i.autojournal.fr/feed/",
      "https://partner-feeds.lessentiel.lu/rss/lessentiel-fr/sports/formule-1",
      "https://le10sport.com/fr/rss/formule1/",
      "https://www.sportmag.fr/category/formule-1/feed/",
      "https://www.rts.ch/sport/auto/?format=rss/news",
      "https://rss.rtbf.be/article/rss/highlight_rtbf_sport-moteurs-formule-1.xml?source=internal",
      "https://rmcsport.bfmtv.com/rss/auto-moto/f1/",
      "https://www.f1actu.com/feed/",
      "https://www.f1-fansite.com/feed/",
    ],
  },
  {
    name: "F1 News EN",
    emoji: "🇬🇧",
    channelId: "1470725269714108542",
    feedUrls: [
      "https://www.motorsport.com/rss/f1/news/",
      "https://www.autosport.com/rss/f1/news/",
      "https://www.autosport.com/rss/f1/videos/",
      "https://racer.com/f1/feed",
      "https://www.motorsport.com/rss/f1/videos/",
      "http://www.f1reader.com/rss/f1r",
      "https://www.formula1.com/en/latest/all.xml",
      "https://feeds.bbci.co.uk/sport/formula1/rss.xml",
      "https://www.gpfans.com/en/rss.xml",
      "https://www.f1technical.net/rss/news.xml",
      "https://speedcafe.com/f1/feed/",
      "https://paddockmagazine.com/feed/",
      "https://f1-analysis.com/feed/",
      "https://www.the-race.com/category/formula-1/rss/",
      "https://www.racefans.net/category/formula-1/feed/",
      "https://www.grandprix247.com/sitemap/news.xml",
      "https://www.thef1spectator.com/feed/",
    ],
  },
  {
    name: "WRC News FR",
    emoji: "🇫🇷",
    channelId: "1376596690022170698",
    feedUrls: [
      "https://sports.auto-moto.com/rss/rallye.html",
      "https://fr.motorsport.com/rss/wrc/news/",
      "https://rallye-sport.ouest-france.fr/feed/",
      "https://rss.rtbf.be/article/rss/highlight_rtbf_sport-moteurs-rallye.xml?source=internal",
      "https://fr.motorsport.com/rss/wrc/videos/",
      "https://www.sportmag.fr/category/rallye/feed/",
      "https://dwh.lequipe.fr/api/edito/rss?path=/Rallye/",
      "https://dwh.lequipe.fr/api/edito/rss?path=/Auto-moto/Wrc/",
      "https://planetemarcus.com/feed/",
    ],
  },
  {
    name: "WRC News EN",
    emoji: "🇬🇧",
    channelId: "1470745727582994546",
    feedUrls: [
      "https://www.motorsport.com/rss/category/rally/news/",
      "https://dirtfish.com/rally/wrc/feed/",
      "https://www.motorsport.com/rss/category/rally/videos/",
      "https://www.autosport.com/rss/wrc/news/",
      "https://rallypromoter.ca/category/wrc/feed/",
      "https://www.wrcwings.tech/feed/",
      "https://www.crash.net/rss/wrc",
      "https://www.bsimracing.com/category/wrc/feed/",
      "https://rallyjournal.com/feed/",
    ],
  },
      {
    name: "Toyota WRC",
    emoji: "🔴",
    channelId: "1468619853538791436",
    feedUrls: [
      "https://toyota-racing-newsroom.com/rss/wrc.rss",
      "https://politepaul.com/fd/oMmn3ed9e34R.xml",
      "https://news.google.com/rss/search?q=Toyota%20WRC&hl=en-US&gl=US&ceid=US%3Aen",
    ],
  },
  {
    name: "Hyundai WRC",
    emoji: "🔵",
    channelId: "1468619813415813201",
    feedUrls: [
      "https://politepaul.com/fd/EkrHAwd6VycR.xml",
      "https://news.google.com/rss/search?q=Hyundai%20WRC&hl=en-US&gl=US&ceid=US%3Aen",
    ],
  },
  {
    name: "M-Sport WRC",
    emoji: "⚪",
    channelId: "1468619906055409675",
    feedUrls: [
      "https://politepaul.com/fd/yjYQuN3EpZgw.xml",
      "https://news.google.com/rss/search?q=M%20Sport%20WRC&hl=en-US&gl=US&ceid=US%3Aen",
    ],
  },
];
